<?php
//template was generated by Alchemist - Joomla! module generator, http://alchemist-rad.ru/

/**
 * Helper class for module mod_learn
 * @package mod_learn
 * @version 1.0
 * @author Patrick, <dev@patric.xyz>
 * @link http://patric.xyz
 * @license GNU GPL
 */
defined('_JEXEC') or die;
class ModlearnHelper
{
	
}
